### PR TITLE
Adding a decoration option to add an image as a background

### PR DESCRIPTION
**Pull request by freshteapot**
Example usage:

```
controller.decorationForPainter = new BoxDecoration(
      image: new DecorationImage(
        image: ExactAssetImage('assets/bg.jpg'),
      ),
    );
```

I am not sure if this is the best approach, as I am still quite new to flutter. Equally this does not satisfy the issue request (#3 ) of using an image from the gallery.

### CODE REVIEW

**Comment by gedw99** [comment]
Is this likely to be merged ?
I also need this functionality.

**Comment by EP-u-NW** [comment]
Hi, after reviewing your code, I don't understand, how the decoration is actually applied.
You declare it, but where do you use it?

**Comment by tmarzeion** [comment]
Actually what this PR do is adding `Decoration` field with proper setter/getter, but that's all.
There are 2 things that should be done to make it proper PR:
1. Do something with `_decorationForPainter` in `painter.dart`, because its unused ATM.
2. IMHO its much better to make some method that would take image as parameter (as asset path, as byte array or something like that) instead of `Decorator` so that logic is on library side.

**Comment by aravindhkumar23** [comment]
@gedw99 

Here is my[ pull request](https://github.com/EPNW/painter/pull/22) for work around to set the background.

Hope this helps some one to achieve it.

**Comment by freshteapot** [comment]
No problem for closing it, it was mostly to show a way to do it.
I am still far too new, to know how best to do it in flutter.

**Pull request closed without merging**
